---
name: "Build"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          apt-get update -y
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint -U
          pip install pyinstaller

      # - name: Lint
      #   run: |
      #     pylint ./*.py

      - name: Run tests
        run: |
          python -m unittest discover -p '*_unittest.py'

      - name: Build
        run: |
          pyinstaller -F client.py --name z-monit -w --icon=templates/static/logo.ico
