---
name: "Tests"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up python
        run: |
          # install python3.10 and pip
          apt update
          apt install -y python3.10 python3.10-distutils
          # Ensure python3.10 is used as python
          update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1
          update-alternatives --install /usr/bin/python python /usr/bin/python3.10 1
          update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python test_Database_unittest.py
